logging:
  level:
    org:
      springframework:
        web: DEBUG
server:
  port: 8001
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devops?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml